<p align="justify">Membership and Insurance are annual for 12 months from the date of activation. Membership and premium prices are shown in Australian dollars (AUD$). Your membership and insurance are not activated until acceptance and processing by DAN AP and confirmation of valid payment. Payment must accompany application. Processing time is within 1 week unless <a href="http://www.danasiapacific.org/main/popups/fastprocessing.php" rel="popup console 670 525 noicon">Fast Processing</a> is requested. Please allow sufficient time for your local postal services to deliver your Membership Pack, which may take several weeks depending on your location. Please ensure that your membership is arranged in advance of an anticipated trip. </p>
<p align="justify">Availability of services and benefits for evacuation or injury commences on acceptance of an application for membership of DAN AP. The applicant is required to complete the application fully and in good faith. No cover is provided for any evacuation, medical, paramedical or other injury benefits resulting from or materially contributed to, directly or indirectly by any diving or other activity in which the applicant engaged prior to and up to the time of acceptance of the application by DAN AP, regardless of the date on which any claim for cover is made by or on behalf of the applicant. </p>
<p align="justify">NOTE: 10% GST, the relevant stamp duty and administration fee are included in the prices of all memberships and insurances in Australia, as appropriate.</p>
<p align="justify">DAN AP ABN 67 066 827 129 (Corporate Authorised Representative Licence No. 269340) is an Authorised Representative of Marsh   Advantage Insurance Pty Ltd (ABN 31081 358 303, AFSL. 238   369).  A <a href="http://www.danasiapacific.org/main/_pdf/fsgcurrent.pdf">Financial Services Guide</a>   is available from DAN AP and on this website which provides important information about DAN AP's relationship and is intended to assist you in your decision whether to use any of our services. <br />
  <br />
<strong>General Advice Warning</strong> &ndash; It is important that you understand and are happy  with the policy DAN AP can arrange for you. DAN AP can give you general  information to help you decide but cannot advise you on whether the terms are  specifically appropriate for your individual objectives, financial situation or  needs. DAN AP therefore recommends that you should carefully read the relevant  Product Disclosure Statement and other information DAN AP provides before  deciding.</p>
<p align="justify">  <strong>DISCLOSURE</strong><br />
  Before you enter into a contract of general insurance with an insurer, you have  a duty, under the Insurance Contracts Act 1984, to disclose to the insurer  every matter that you know, or could reasonably be expected to know, is  relevant to the insurer's decision whether to accept the risk of the insurance  and, if so, on what terms.<br />
  Your duty, however, does not require disclosure of matters: <br />
&middot;&nbsp;&nbsp;that diminish the risk to be undertaken by the insurer,<br />
&middot;&nbsp;&nbsp;that are of common knowledge, <br />
&middot;&nbsp;&nbsp;that your insurer knows or, in the ordinary course of its  business, ought to know, or <br />
&middot;&nbsp;&nbsp;as to which compliance with your duty is waived by the insurer. <br />
<br />
If you enter into a contract of insurance on behalf of any related subsidiary or related company of the named insured, that subsidiary or related company has the same duty of disclosure as the named insured. You agree to act on behalf of all insureds under this insurance.</p>
<p align="justify">Non-Disclosure <br />
  If you fail to comply with your duty of disclosure, the insurer may be entitled  to reduce its liability under the contract in respect of a claim, or may cancel  the contract. If your non-disclosure is fraudulent, the insurer may also have  the option of avoiding the contract from its beginning.&nbsp;PLEASE NOTE THAT  YOUR DUTY APPLIES ALSO WHEN YOU RENEW, AMEND, ALTER, VARY OR ENDORSE A POLICY.</p>
<p align="justify"><strong>UTMOST GOOD FAITH</strong><br />
  Every insurance contract is subject  to the doctrine of utmost good faith, which requires that parties to the  contract should act toward each other honestly and fairly, avoiding any attempt  to deceive in assuming and performing contractual obligations. Failure to do so  on the part of the insured may permit the insurer to refuse to pay a claim or  to cancel the policy.</p>
<p align="justify"><strong>Product Disclosure Statement</strong><br />
A Product Disclosure Statement is available for this  product.&nbsp;You should obtain a copy of the PDS and consider the statement  before making any&nbsp;decision about whether to acquire the product.&nbsp; To  obtain a copy of the PDS contact DAN AP or <a href="http://www.danasiapacific.org/main/_pdf/pdscurrent.pdf">click here</a> to download a copy&nbsp;.&nbsp;  This product is underwritten and issued by Certain Underwriters at  Lloyds.&nbsp;</p>
<p align="justify">By submitting this form the  proposed Insured Person states as follows:<br />
1. All Applicants for insurance in this form are Australian Nationals or will  legally reside in Australia for at least one year.<br />
2. I am the Insured Person and I have read and understood the questions in this  form. In particular I understand the Duty of Disclosure to the Insurer as  outlined on this website.<br />
3. I acknowledge that the Insurer will rely on the statements in this form and  other qualified persons in relation to this insurance in deciding whether to  issue cover. I acknowledge that the Insurer will have no liability whatsoever  until it accepts this application.<br />
4. I declare that each statement that I make to the Insurer in relation to this  insurance and this form is true and correct. I acknowledge that the information  requested and contained in this form will be held in accordance with the  Privacy Act1988 (Commonwealth).<br />
5. I declare that I have read the Product Disclosure Statement and Financial  Services Guide and agree to the conditions outlined.</p>
