<div align="justify">
  <p>Membership is annual for 12 months from the date of activation. Membership and premium prices are shown in Australian dollars (AUD$). Your membership is not activated until acceptance and processing by DAN AP and confirmation of valid payment. Payment must accompany application. Processing time is within 1 week unless <a href="http://www.danasiapacific.org/main/popups/fastprocessing.php" rel="popup console 670 525 noicon">Fast Processing</a>  is requested. Please allow sufficient time for your local postal services to deliver your Membership Pack, which may take several weeks depending on your location. Please ensure that your membership is arranged in advance of an anticipated trip.</p>
  <p>Availability of services and benefits for evacuation or injury commences on acceptance of an application for membership of DAN AP. The applicant is required to complete the application fully and in good faith.</p>
  <p><strong>UTMOST GOOD FAITH</strong><br />
  The Assistance obligations,  under DAN Membership, are subject to the doctrine of Utmost Good Faith, which  requires that parties to the contract should act toward each other honestly and  fairly, avoiding any attempt to deceive in assuming and performing contractual  obligations. Failure to do so on the part of the Member may permit DAN to refuse  to pay for or arrange assistance or other services. </p>
  <p>    The applicant is required to  complete the application fully and in good faith. No cover is provided for any  evacuation, medical, paramedical or other injury benefits resulting from or  materially contributed to, directly or indirectly by any diving or other  activity in which the applicant engaged prior to and up to the time of  acceptance of the application by DAN AP, regardless of the date on which any  claim for cover is made by or on behalf of the applicant.</p>
  <p>    NOTE: 10% GST, the  relevant stamp duty and administration fee are included in the prices of all  memberships and insurances in Australia, as appropriate.</p>
  <br />
</div>
